<a href="https://colab.research.google.com/github/alaycheme25/chemeng277_batteryproject/blob/main/machine_learning_3_5_after_meeting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install mp-api pymatgen periodictable paretoset

Requirement already satisfied: mp-api in /usr/local/lib/python3.12/dist-packages (0.46.0)
Requirement already satisfied: pymatgen in /usr/local/lib/python3.12/dist-packages (2025.10.7)
Requirement already satisfied: periodictable in /usr/local/lib/python3.12/dist-packages (2.1.0)
Requirement already satisfied: paretoset in /usr/local/lib/python3.12/dist-packages (1.2.5)
Requirement already satisfied: typing-extensions>=3.7.4.1 in /usr/local/lib/python3.12/dist-packages (from mp-api) (4.15.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from mp-api) (2.32.4)
Requirement already satisfied: monty>=2024.12.10 in /usr/local/lib/python3.12/dist-packages (from mp-api) (2026.2.18)
Requirement already satisfied: emmet-core>=0.86.3 in /usr/local/lib/python3.12/dist-packages (from mp-api) (0.86.3)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from mp-api) (1.42.62)
Requirement already satisfied: orjson<4,>=3.10 in /usr/local/lib/python3.12/dist-packages (from mp-api) (3.11.7)
Requirement already satisfied: bibtexparser>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.4.4)
Requirement already satisfied: joblib>=1 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.5.3)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.10.0)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.6.1)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.0.2)
Requirement already satisfied: palettable>=3.3.3 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.3.3)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.2.2)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (5.24.1)
Requirement already satisfied: ruamel.yaml>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (0.19.1)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.16.3)
Requirement already satisfied: spglib>=2.5 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.7.0)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.14.0)
Requirement already satisfied: tabulate>=0.9 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (0.9.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (4.67.3)
Requirement already satisfied: uncertainties>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.2.3)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from periodictable) (3.3.2)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from paretoset) (0.60.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from emmet-core>=0.86.3->mp-api) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from emmet-core>=0.86.3->mp-api) (2.13.1)
Requirement already satisfied: pymatgen-io-validation>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from emmet-core>=0.86.3->mp-api) (0.1.2)
Requirement already satisfied: pybtex~=0.24 in /usr/local/lib/python3.12/dist-packages (from emmet-core>=0.86.3->mp-api) (0.25.1)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from emmet-core>=0.86.3->mp-api) (1.0.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->pymatgen) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->pymatgen) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->pymatgen) (9.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->mp-api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->mp-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->mp-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->mp-api) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->pymatgen) (1.3.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.62 in /usr/local/lib/python3.12/dist-packages (from boto3->mp-api) (1.42.62)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->mp-api) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->mp-api) (0.16.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->paretoset) (0.43.0)
Requirement already satisfied: PyYAML>=3.01 in /usr/local/lib/python3.12/dist-packages (from pybtex~=0.24->emmet-core>=0.86.3->mp-api) (6.0.3)
Requirement already satisfied: latexcodec>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pybtex~=0.24->emmet-core>=0.86.3->mp-api) (3.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->emmet-core>=0.86.3->mp-api) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->emmet-core>=0.86.3->mp-api) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->emmet-core>=0.86.3->mp-api) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->emmet-core>=0.86.3->mp-api) (1.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->pymatgen) (1.17.0)

### Importing necessary packages and files

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.decomposition import PCA
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import paretoset
import periodictable
from pymatgen.core import Structure
import ast
from sklearn.linear_model import ElasticNet

In [3]:
pdata = pd.read_excel("MATSCI_176_Project_Data.xlsx")
pdata.head()

,battery_formula,working_ion,elements,nelements,formula_charge,formula_discharge,max_delta_volume,average_voltage,capacity_grav,capacity_vol,...,stability_charge,stability_discharge,electrode_density,material_density,working_ion_cost_per_kWh,structure,formation_energy_per_atom,band_gap,energy_density,battery_cost_per_L
0,Li0-3Ag,Li,['Ag'],1.0,Ag,Li3Ag,2.736089,0.210565,624.785871,1984.816229,...,0.003609,0.000000,3.176794,2.592432,10.0,"{'@module': 'pymatgen.core.structure', '@class...",0.333634,0,417.933696,4.179337
1,Li0-3Sb,Li,['Sb'],1.0,Sb,Li3Sb,1.569237,1.015953,563.913254,1890.293779,...,0.328351,0.000000,3.352100,3.378028,10.0,"{'@module': 'pymatgen.core.structure', '@class...",-0.744135,0.7074,1920.448911,19.204489
2,Li0-1Bi,Li,['Bi'],1.0,Bi,LiBi,0.368255,0.796796,124.126099,923.538664,...,0.049545,0.000000,7.440326,2.237712,10.0,"{'@module': 'pymatgen.core.structure', '@class...",-0.034716,0,735.871648,7.358716
3,Li0-3Ce,Li,['Ce'],1.0,Ce,Li3Ce,2.951183,-0.444846,499.595769,1295.168213,...,0.000000,0.333634,2.592432,2.583328,10.0,"{'@module': 'pymatgen.core.structure', '@class...",-0.330999,0,576.149771,5.761498
4,Li0-3Ca,Li,['Ca'],1.0,Ca,Li3Ca,1.513956,-0.064931,1320.248328,1271.741142,...,0.000000,0.057445,0.963259,7.527518,10.0,"{'@module': 'pymatgen.core.structure', '@class...",-0.415156,0,82.574983,0.825750

In [4]:
structures = pdata["structure"]
print(structures.shape)
structure_dict_test = ast.literal_eval(structures[1])
structure_test = Structure.from_dict(structure_dict_test)
print(structure_test)
print(structure_test.lattice.abc)
print(structure_test.volume)

(5786,)
Full Formula (Li3 Sb1)
Reduced Formula: Li3Sb
abc   :   4.627959   4.627959   4.627959
angles:  60.000007  60.000010  60.000007
pbc   :       True       True       True
Sites (4)
  #  SP       a      b     c    magmom
---  ----  ----  -----  ----  --------
  0  Li    0.5    0.5   0.5          0
  1  Li    0.25   0.25  0.25        -0
  2  Li    0.75   0.75  0.75        -0
  3  Sb    0     -0     0            0
(4.627959209506349, 4.627958733729667, 4.62795882)
70.08959778250679

In [5]:
def get_volume(structure_str):
    try:
        structure_dict = ast.literal_eval(structure_str)
        structure = Structure.from_dict(structure_dict)
        return structure.volume
    except:
        return np.nan
structure_volums = pdata["structure"].apply(get_volume) # Volumes in Angstrom^3
def get_abc(structure_str):
    try:
        structure_dict = ast.literal_eval(structure_str)
        structure = Structure.from_dict(structure_dict)
        return structure.lattice.abc
    except:
        return np.nan
# structure_abc = pdata["structure"].apply(get_abc) # abc values in Angstrom
# structure_abc_df = pd.DataFrame(structure_abc.tolist(), columns=['a', 'b', 'c'])
pdata = pdata.drop(columns=["structure"], axis=1)

In [6]:
structure_volums = structure_volums.to_frame()
structure_volums = structure_volums.fillna(0)
structure_volums = structure_volums["structure"]
pdata["structure_volume"] = structure_volums.values

In [7]:
pdata.head()

,battery_formula,working_ion,elements,nelements,formula_charge,formula_discharge,max_delta_volume,average_voltage,capacity_grav,capacity_vol,...,stability_charge,stability_discharge,electrode_density,material_density,working_ion_cost_per_kWh,formation_energy_per_atom,band_gap,energy_density,battery_cost_per_L,structure_volume
0,Li0-3Ag,Li,['Ag'],1.0,Ag,Li3Ag,2.736089,0.210565,624.785871,1984.816229,...,0.003609,0.000000,3.176794,2.592432,10.0,0.333634,0,417.933696,4.179337,103.086779
1,Li0-3Sb,Li,['Sb'],1.0,Sb,Li3Sb,1.569237,1.015953,563.913254,1890.293779,...,0.328351,0.000000,3.352100,3.378028,10.0,-0.744135,0.7074,1920.448911,19.204489,70.089598
2,Li0-1Bi,Li,['Bi'],1.0,Bi,LiBi,0.368255,0.796796,124.126099,923.538664,...,0.049545,0.000000,7.440326,2.237712,10.0,-0.034716,0,735.871648,7.358716,58.627385
3,Li0-3Ce,Li,['Ce'],1.0,Ce,Li3Ce,2.951183,-0.444846,499.595769,1295.168213,...,0.000000,0.333634,2.592432,2.583328,10.0,-0.330999,0,576.149771,5.761498,1918.735425
4,Li0-3Ca,Li,['Ca'],1.0,Ca,Li3Ca,1.513956,-0.064931,1320.248328,1271.741142,...,0.000000,0.057445,0.963259,7.527518,10.0,-0.415156,0,82.574983,0.825750,47.631359

In [8]:
numeric_cols = [
    "material_density",
    "formation_energy_per_atom",
    "band_gap"
]

for col in numeric_cols:
    pdata[col] = pd.to_numeric(pdata[col], errors="coerce")
pdata = pdata.dropna()
pdata = pdata.reset_index(drop=True)
pdata.head()

,battery_formula,working_ion,elements,nelements,formula_charge,formula_discharge,max_delta_volume,average_voltage,capacity_grav,capacity_vol,...,stability_charge,stability_discharge,electrode_density,material_density,working_ion_cost_per_kWh,formation_energy_per_atom,band_gap,energy_density,battery_cost_per_L,structure_volume
0,Li0-3Ag,Li,['Ag'],1.0,Ag,Li3Ag,2.736089,0.210565,624.785871,1984.816229,...,0.003609,0.000000,3.176794,2.592432,10.0,0.333634,0.0000,417.933696,4.179337,103.086779
1,Li0-3Sb,Li,['Sb'],1.0,Sb,Li3Sb,1.569237,1.015953,563.913254,1890.293779,...,0.328351,0.000000,3.352100,3.378028,10.0,-0.744135,0.7074,1920.448911,19.204489,70.089598
2,Li0-1Bi,Li,['Bi'],1.0,Bi,LiBi,0.368255,0.796796,124.126099,923.538664,...,0.049545,0.000000,7.440326,2.237712,10.0,-0.034716,0.0000,735.871648,7.358716,58.627385
3,Li0-3Ce,Li,['Ce'],1.0,Ce,Li3Ce,2.951183,-0.444846,499.595769,1295.168213,...,0.000000,0.333634,2.592432,2.583328,10.0,-0.330999,0.0000,576.149771,5.761498,1918.735425
4,Li0-3Ca,Li,['Ca'],1.0,Ca,Li3Ca,1.513956,-0.064931,1320.248328,1271.741142,...,0.000000,0.057445,0.963259,7.527518,10.0,-0.415156,0.0000,82.574983,0.825750,47.631359

In [9]:
pdata_norm = pdata.iloc[:, 6:]
print(pdata_norm.columns)

Index(['max_delta_volume', 'average_voltage', 'capacity_grav', 'capacity_vol',
       'energy_grav', 'energy_vol', 'stability_charge', 'stability_discharge',
       'electrode_density', 'material_density', 'working_ion_cost_per_kWh',
       'formation_energy_per_atom', 'band_gap', 'energy_density',
       'battery_cost_per_L', 'structure_volume'],
      dtype='object')

#### Defining our scoring function(s) to analyze and their input datasets.
We don't want to train our model on the features which are used for scoring. Therefore, we need to define a new training dataset excluding these features. Our scoring model uses gravimetric energy, gravimetric capacity, battery cost per liter, energy density, and battery voltage, so we removed these from our training data set. Additionally, features like energy volume, capacity volume, and electrode density are correlated with battery cost and energy density (as they're used in the calculations for those features), so we removed those columns from our training data to avoid any overlap.

In [10]:
# Getting the energy grav, capacity grav, battery cost per L, energy density, and average voltage columns for scoring and removing those and additional columns from the training data
# energy_grav = pdata_norm["energy_grav"]
cap_grav = pdata_norm["capacity_grav"]
battery_cost = pdata_norm["battery_cost_per_L"]
energy_density = pdata_norm["energy_density"]
voltage = pdata_norm['average_voltage']
training_data = pdata_norm.drop(columns=["energy_grav", "capacity_grav", "battery_cost_per_L", "energy_density", "average_voltage", "energy_vol", "capacity_vol", "electrode_density", "max_delta_volume", "stability_charge"])

# Creating a new training dataset without cost to benchmark our scoring with and without cost, since our cost is not from the same source (Materials Project)
training_data_nocost = training_data.drop(columns=["working_ion_cost_per_kWh"])

In [11]:
def scoring_nocost(c_g,e_d,v):
    # e_g = e_g.to_numpy().astype(float)
    c_g = c_g.to_numpy().astype(float)
    e_d = e_d.to_numpy().astype(float)
    v = v.to_numpy().astype(float)
    score = 0.4*(np.abs(e_d)-np.min(e_d))/(np.max(e_d)-np.min(e_d)) + 0.4*(np.abs(c_g)-np.min(c_g))/((np.max(c_g))-np.min(c_g)) + 0.2*(np.abs(v)-np.min(np.abs(v)))/(np.max(v)-np.min(np.abs(v)))
    # score = abs(e_g) + abs(c_g) + abs(e_d) + abs(v)
    return pd.Series(score)

def scoring_withcost(c_g,b_c,e_d,v):
    # e_g = e_g.to_numpy().astype(float)
    c_g = c_g.to_numpy().astype(float)
    b_c = b_c.to_numpy().astype(float)
    e_d = e_d.to_numpy().astype(float)
    v = v.to_numpy().astype(float)
    score = np.abs(e_d)/np.max(e_d) + np.abs(c_g/b_c)/(np.max(c_g)/np.max(b_c)) + np.abs(v)/np.max(v)
    # score = abs(e_g) + abs(c_g) - abs(b_c) + abs(e_d) + abs(v)
    return pd.Series(score)

### Benchmarking the Ridge & Elastic Net Regressional Models
We chose ridge regression and elasticnet regression to both identify important features (from the ridge component) while zeroing out features which don't affect battery performance (features that don't affect our score.)

In [12]:
# Testing the no-cst scoring function and defining our fit & training datasets.
battery_score = scoring_nocost(cap_grav, energy_density, voltage)

fit_train, fit_test, score_train, score_test = train_test_split(
    training_data_nocost,
    battery_score,
    test_size=0.1,
    random_state=42
)

# Normalization of the fit and training datasets for better performance of the elastic net model, since it is sensitive to the scale of the features
norm_fit_train = pd.DataFrame(
    StandardScaler().fit_transform(fit_train),
    columns=fit_train.columns
)
norm_fit_test = pd.DataFrame(
    StandardScaler().fit_transform(fit_test),
    columns=fit_test.columns
)

In [13]:
ridge = linear_model.Ridge(alpha=1.0).fit(norm_fit_train, score_train, sample_weight=None)
score_pred = ridge.score(norm_fit_test, score_test)
print(f"Effective R^2 score: {score_pred:.3f}")

Effective R^2 score: 0.028

In [14]:
best = np.where(battery_score == np.max(battery_score))[0][0]
# print(pdata_norm.iloc[best])
print(pdata.iloc[best])
# print(len(pdata["capacity_grav"]))
# print(len(pdata_norm["capacity_grav"]))
print("Battery Score:", np.max(battery_score))
# print(energy_grav.iloc[best], cap_grav.iloc[best], energy_density.iloc[best], voltage.iloc[best])

battery_formula                Li1-3Ti2(PO4)3
working_ion                                Li
elements                     ['Ti', 'P', 'O']
nelements                                 3.0
formula_charge                    LiTi2(PO4)3
formula_discharge                Li3Ti2(PO4)3
max_delta_volume                     0.086321
average_voltage                     33.065771
capacity_grav                      133.516371
capacity_vol                       421.348595
energy_grav                       4414.821755
energy_vol                       13932.216223
stability_charge                     3.516172
stability_discharge                  0.074915
electrode_density                    3.155782
material_density                     5.482777
working_ion_cost_per_kWh                 10.0
formation_energy_per_atom           -2.067682
band_gap                                  0.0
energy_density                   13932.216223
battery_cost_per_L                 139.322162
structure_volume                   175.556161
Name: 3204, dtype: object
Battery Score: 0.6235558763107458

Looks pretty decent! We expected a lithium battery to be the best performing battery due to it's electrochemical properties.

## Performing K-folds cross validation on our ridge regressional model.
Choosing k-folds is important to determine if our train-validation split was truely indicative of the full system.

In [15]:
X = training_data_nocost
y = battery_score
y = y.fillna(0)
y = y.astype(float)

In [16]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", linear_model.Ridge(alpha=3.0)) # We chose alpha = 3.0 to weight against sparsity in our features.
])

In [17]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

r2_scores = []
MAE = []
MSE = []
bestmaterial = []

for train_idx, test_idx in kf.split(X):

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    #Find best material in predicted set
    bestmaterial.append(X_test.iloc[np.where(y_pred == np.max(y_pred))[0][0]])

    r2_scores.append(r2_score(y_test, y_pred))
    MSE.append(mean_squared_error(y_test, y_pred))
    MAE.append(mean_absolute_error(y_test, y_pred))

print("Mean R2:", np.mean(r2_scores))
print("Mean MSE:", np.mean(MSE))
print("Mean MAE:", np.mean(MAE))
bestmaterial_df = pd.DataFrame(bestmaterial)
bestmaterial_df

Mean R2: 0.03525312350408598
Mean MSE: 0.002746618148578866
Mean MAE: 0.03890975954867328

,stability_discharge,material_density,formation_energy_per_atom,band_gap,structure_volume
4098,0.00000,4.322285,3.615826,0.0,101.329084
604,0.00000,1.885992,0.700918,0.0,109.893911
6,0.01007,1.481680,0.426453,0.0,36.797188
1796,0.01340,3.172677,0.838711,0.0,176.809733
608,0.00000,1.816624,1.064513,0.0,74.022197

In [18]:
# Converting the best material features back to the original scale for comparison with the original dataset, since we normalized the training & test data.
# To do so, we took the best material from each fold and compared their features to the original datasets to find the approximated battery  (the battery formula with the smallest minimum difference between predicted best and the rest of the dataset).
for i in range(len(bestmaterial)):
    best_material = bestmaterial_df.iloc[i]
    min_diff = float('inf')
    best_match_index = -1
    for j in range(len(pdata)):
        diff = np.sum(np.abs(best_material - pdata.iloc[j, 6:6+len(best_material)]))
        if diff < min_diff:
            min_diff = diff
            best_match_index = j
    print(f"Best material in fold {i+1}:")
    print(pdata.iloc[best_match_index, 0])

Best material in fold 1:
Li0-3Ag
Best material in fold 2:
Li0-3Ag
Best material in fold 3:
Li0-3Ag
Best material in fold 4:
Li0-3Ag
Best material in fold 5:
Li0-3Ag

## Testing Elastic Net Regression in the same way as Ridge Regression

In [19]:
alpha = 1
l1_ratio = 0.5  # 0=ridge-like, 1=lasso-like

enet_pipeline = Pipeline([
    ("enet", ElasticNet(alpha=alpha, l1_ratio=l1_ratio, max_iter=20000, random_state=42))
])

score_pred_enet = enet_pipeline.fit(fit_train, score_train).score(fit_test, score_test)
print("ElasticNet test R^2:", score_pred_enet)

ElasticNet test R^2: 0.0037803172393754414

In [20]:
#replace Ridge KFold with Elastic Net KFold

X = training_data_nocost
y = battery_score.fillna(0).astype(float)

# Elastic Net hyperparameters
alpha = 1
l1_ratio = 0.5

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("enet", ElasticNet(alpha=alpha, l1_ratio=l1_ratio, max_iter=20000, random_state=42))
])

kf = KFold(n_splits=5, shuffle=True, random_state=42)

r2_scores = []
MAE = []
MSE = []
bestmaterial = []

for train_idx, test_idx in kf.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    # store best predicted sample in this fold (same idea as your ridge code)
    bestmaterial.append(X_test.iloc[np.argmax(y_pred)])

    r2_scores.append(r2_score(y_test, y_pred))
    MSE.append(mean_squared_error(y_test, y_pred))
    MAE.append(mean_absolute_error(y_test, y_pred))

print("Mean R^2:", np.mean(r2_scores))
print("Mean MSE:", np.mean(MSE))
print("Mean MAE:", np.mean(MAE))

bestmaterial_df = pd.DataFrame(bestmaterial)
bestmaterial_df

Mean R^2: -0.0027740444405376153
Mean MSE: 0.002853115912168843
Mean MAE: 0.03953833940083366

,stability_discharge,material_density,formation_energy_per_atom,band_gap,structure_volume
8,0.002960,0.946023,0.046672,0.0000,106.898527
19,0.020862,4.829614,-1.304004,0.0000,31.265978
0,0.000000,2.592432,0.333634,0.0000,103.086779
1,0.000000,3.378028,-0.744135,0.7074,70.089598
3,0.333634,2.583328,-0.330999,0.0000,1918.735425

In [21]:
for i in range(len(bestmaterial)):
    best_material = bestmaterial_df.iloc[i]
    min_diff = float('inf')
    best_match_index = -1
    for j in range(len(pdata)):
        diff = np.sum(np.abs(best_material - pdata.iloc[j, 6:6+len(best_material)]))
        if diff < min_diff:
            min_diff = diff
            best_match_index = j
    print(f"Best material in fold {i+1}:")
    print(pdata.iloc[best_match_index, 0])

Best material in fold 1:
Li0-3Ag
Best material in fold 2:
Li0-3Ag
Best material in fold 3:
Li0-3Ag
Best material in fold 4:
Li0-3Ag
Best material in fold 5:
Li0-3Ag

## Testing on other DFT-based features from materials project:
Testing to see if our model & scoring function can predict the quality of a battery based on untrained features, which still correlate with battery lifetime and hence the score.

In [22]:
test_data = pd.read_csv("test_data.csv")
test_data.head()

,formula_pretty,density,material_id,structure,formation_energy_per_atom,energy_above_hull,band_gap,fields_not_requested
0,K3LiP2O7,2.511335,mp-cgaow,"{'@module': 'pymatgen.core.structure', '@class...",-2.671974,0.0,5.0761,"['builder_meta', 'nsites', 'elements', 'neleme..."
1,Rb2LiSbCl6,3.060150,mp-clfam,"{'@module': 'pymatgen.core.structure', '@class...",-1.878165,0.0,2.9411,"['builder_meta', 'nsites', 'elements', 'neleme..."
2,Rb2LiBiCl6,3.317268,mp-clfaq,"{'@module': 'pymatgen.core.structure', '@class...",-1.932272,0.0,3.6154,"['builder_meta', 'nsites', 'elements', 'neleme..."
3,K2LiBiCl6,2.867108,mp-clfht,"{'@module': 'pymatgen.core.structure', '@class...",-1.894874,0.0,3.6182,"['builder_meta', 'nsites', 'elements', 'neleme..."
4,K2LiGaF6,3.349747,mp-clfrc,"{'@module': 'pymatgen.core.structure', '@class...",-3.104615,0.0,6.1271,"['builder_meta', 'nsites', 'elements', 'neleme..."

In [23]:
structures = test_data["structure"]
print(structures.shape)
structure_dict_test = ast.literal_eval(structures[1])
structure_test = Structure.from_dict(structure_dict_test)
print(structure_test)
print(structure_test.lattice.abc)
print(structure_test.volume)

(556,)
Full Formula (Rb2 Li1 Sb1 Cl6)
Reduced Formula: Rb2LiSbCl6
abc   :   7.325951   7.325951   7.325951
angles:  60.000000  60.000000  60.000000
pbc   :       True       True       True
Sites (10)
  #  SP           a          b         c    magmom
---  ----  --------  ---------  --------  --------
  0  Rb    0.75       0.75      0.75             0
  1  Rb    0.25       0.25      0.25             0
  2  Li    0.5        0.5       0.5             -0
  3  Sb    0         -0         0               -0
  4  Cl    0.745526   0.254474  0.254474        -0
  5  Cl    0.254474   0.254474  0.745526        -0
  6  Cl    0.254474   0.745526  0.745526        -0
  7  Cl    0.254474   0.745526  0.254474        -0
  8  Cl    0.745526   0.254474  0.745526        -0
  9  Cl    0.745526   0.745526  0.254474        -0
(7.3259512676535365, 7.3259512676535365, 7.3259512676535365)
278.0206653745919

In [24]:
def get_volume(structure_str):
    try:
        structure_dict = ast.literal_eval(structure_str)
        structure = Structure.from_dict(structure_dict)
        return structure.volume
    except:
        return np.nan
structure_volums = test_data["structure"].apply(get_volume) # Volumes in Angstrom^3
def get_abc(structure_str):
    try:
        structure_dict = ast.literal_eval(structure_str)
        structure = Structure.from_dict(structure_dict)
        return structure.lattice.abc
    except:
        return np.nan

test_data = test_data.drop(columns=["structure"], axis=1)

In [25]:
structure_volums = structure_volums.to_frame()
structure_volums = structure_volums.fillna(0)
structure_volums = structure_volums["structure"]
test_data["structure_volume"] = structure_volums.values

In [26]:
test_data.head()

,formula_pretty,density,material_id,formation_energy_per_atom,energy_above_hull,band_gap,fields_not_requested,structure_volume
0,K3LiP2O7,2.511335,mp-cgaow,-2.671974,0.0,5.0761,"['builder_meta', 'nsites', 'elements', 'neleme...",394.322773
1,Rb2LiSbCl6,3.060150,mp-clfam,-1.878165,0.0,2.9411,"['builder_meta', 'nsites', 'elements', 'neleme...",278.020665
2,Rb2LiBiCl6,3.317268,mp-clfaq,-1.932272,0.0,3.6154,"['builder_meta', 'nsites', 'elements', 'neleme...",300.131828
3,K2LiBiCl6,2.867108,mp-clfht,-1.894874,0.0,3.6182,"['builder_meta', 'nsites', 'elements', 'neleme...",293.543482
4,K2LiGaF6,3.349747,mp-clfrc,-3.104615,0.0,6.1271,"['builder_meta', 'nsites', 'elements', 'neleme...",133.275008

In [27]:
stability_discharge = test_data["energy_above_hull"]
material_density = test_data["density"]
formation_energy_per_atom = test_data["formation_energy_per_atom"]
band_gap = test_data["band_gap"]
structure_volume = test_data["structure_volume"]
test_data_short = pd.DataFrame({
    "stability_discharge": stability_discharge,
    "material_density": material_density,
    "formation_energy_per_atom": formation_energy_per_atom,
    "band_gap": band_gap,
    "structure_volume": structure_volume,
})

In [28]:
test_data_short.head()

,stability_discharge,material_density,formation_energy_per_atom,band_gap,structure_volume
0,0.0,2.511335,-2.671974,5.0761,394.322773
1,0.0,3.060150,-1.878165,2.9411,278.020665
2,0.0,3.317268,-1.932272,3.6154,300.131828
3,0.0,2.867108,-1.894874,3.6182,293.543482
4,0.0,3.349747,-3.104615,6.1271,133.275008

In [29]:
test_pred = ridge.predict(test_data_short)

In [30]:
print(test_pred)

[-1.84735006e+00 -1.28204546e+00 -1.38986404e+00 -1.35641509e+00
 -5.93353689e-01 -1.25471295e+00 -1.37865852e+00 -6.64588755e-01
 -1.73233951e+00 -1.71917878e+00 -1.41244178e+00 -2.16323438e+00
 -1.40203481e+00 -1.43368618e+00 -1.31015657e+00 -2.18046631e+00
 -1.39185721e+00 -6.97473288e-01 -1.30628558e+00 -7.44827987e-01
 -7.11607866e-01 -1.58702447e+00 -1.36017869e+00 -1.58950866e+00
 -1.23863388e+00 -7.15938889e-01 -6.64981216e-01 -1.26609236e+00
 -8.10971597e-01 -9.52979043e-01 -1.35980891e+00 -2.40377233e+00
 -6.92922109e-01 -3.48242397e+00 -1.58521711e+00 -3.55065403e+00
 -1.47836423e+00 -1.31704076e+00 -1.01782104e+00 -3.42219611e+00
 -3.53256586e-01 -3.58120115e-01 -3.41410670e-01 -3.88824271e-01
 -3.84903476e-01 -3.37445511e-01 -3.29417371e-01 -3.97370648e-01
 -3.92905050e-01 -3.33831683e-01 -4.03759262e-01 -9.97658812e-02
 -1.03884264e-01 -3.82738422e-01 -5.77358395e-01 -9.75155386e+00
 -4.24571016e+00 -9.34210034e+00 -2.33064600e+00 -2.63406703e+00
 -1.81320623e-01 -2.82993084e-01 -2.14580828e-01 -7.75879921e-02
 -1.86290512e-01 -3.48652107e-01 -2.44660787e-01 -8.32988548e-01
 -1.46250658e+00 -1.74301372e+00 -1.70008958e+00 -1.47895908e+00
 -7.76331983e-01 -1.72917127e+00 -5.76891144e-01 -9.34755675e-01
 -3.31728477e+00 -3.71941986e+00 -8.78545177e+00 -2.00513955e+00
 -1.07627068e+00 -1.82012456e+00 -1.86671601e+00 -2.91213846e+00
 -1.57410643e+01 -1.55248350e+01 -2.41383215e-01 -1.53276386e-01
 -5.98648812e-02 -1.91190191e-01 -2.69655693e-01 -8.17542310e-01
 -2.05303950e-01 -9.34895555e-01 -2.22334872e+00 -2.35179499e+00
 -1.49601012e+00 -2.29032605e+00 -8.85788331e-01 -2.10165304e+00
 -2.45439001e+00 -5.66924425e-01 -1.50378316e+00 -1.54372723e+00
 -4.92479072e-01 -1.09600234e+00 -1.18652429e+00 -4.09855835e-01
 -2.31067442e-01 -4.96047908e-01 -4.99134627e-01 -1.11816836e+00
 -9.89529098e-01 -1.28522083e+00 -1.12266253e+00 -1.28235064e+00
 -9.32381019e-01 -2.72862950e+00 -1.03874057e+00 -4.47170933e+00
 -9.55735656e-01 -1.05543621e+00 -4.25384045e+00 -1.26559167e+00
 -7.54941566e-01 -9.27044382e-01 -1.34649733e+00 -9.11983959e-01
 -1.28502877e+00 -5.24556190e-01 -2.67720439e+00 -3.35652137e+00
 -3.57528548e+00 -6.99122809e-01 -6.99309297e-01 -1.06139543e+00
 -5.52741093e-01 -5.06713901e-01 -9.20802695e-01 -1.01287376e+01
 -1.27399467e-01 -6.47525990e+00 -5.67120124e-01 -4.18816193e-01
 -3.02209724e-02 -5.72569415e-01 -1.31362445e-03 -2.58529249e+00
 -3.32168724e+00 -3.59514186e-01 -9.53870785e-01 -1.22187235e+00
 -2.20826132e-01 -2.89721519e-01 -1.09837457e+00 -1.09391389e+00
 -1.86046983e-01 -8.05372284e-01 -5.56244176e-01 -6.40665042e-01
 -6.18220382e-01 -3.46820787e-01 -4.35940763e-01 -7.05507627e-01
 -3.03423144e-01 -1.90301884e+00 -9.20779432e-01 -2.28898020e+00
 -9.39510228e-01 -2.76307584e+00 -3.37252765e+00 -2.77891775e+00
 -3.33700874e+00 -4.15119479e-01 -4.61757677e+00 -4.35634315e+00
 -8.92689043e-01 -3.70905339e-01 -4.11890182e-01 -4.50199652e-01
 -4.24070660e-01 -3.78547024e-01 -4.01292462e-01 -3.48126183e-01
 -2.25400887e+00 -1.05773928e+00 -6.08049433e-01 -1.86904035e+01
 -1.30759948e+00 -9.61736200e-01 -1.47781945e+00 -3.35864942e+00
 -2.37076137e+00 -2.39944323e+00 -2.20205045e+00 -2.60883953e+00
 -1.03497147e+00 -2.05408646e+00 -1.78615299e+00 -2.20818779e+00
 -2.02292635e+00 -2.18051468e+00 -2.25540719e+00 -2.12091569e+00
 -2.20171518e+00 -5.25231785e+00 -2.30017975e+00 -2.20743238e+00
 -1.32213375e+00 -1.09303576e+00 -9.42162372e-01 -2.81087976e+00
 -2.84609640e+00 -1.05638579e+00 -1.04417333e+00 -1.00711997e+00
 -8.00298593e-01 -1.68557495e+00 -8.28362151e-01 -1.20396783e+00
 -1.39225748e+00 -1.08448528e+00 -2.67015134e+00 -1.48987813e+00
 -8.49633974e-01 -2.89851251e+00 -1.43325656e+00 -1.08044284e+01
 -1.45963790e+00 -5.98419538e+00 -6.31439468e+00 -4.38912402e+00
 -9.36459771e-01 -2.05764957e+00 -1.34911719e+00 -1.63184183e+00
 -2.43364041e-01 -1.20782903e+00 -1.87083304e+00 -7.21583717e-01
 -7.87160838e-01 -2.72673595e+00 -7.73253911e-01 -1.18076949e+01
 -1.05841431e+00 -1.30379465e+00 -2.86856267e+00 -2.91924663e+00
 -3.47609385e+00 -5.66906324e+00 -5.58919149e+00 -5.36515792e+00
 -5.98638221e+00 -6.21619933e+00 -2.10774641e+00 -1.93995742e+00
 -6.26134362e+00 -2.03786596e+00 -2.16982530e+00 -8.51460862e-01
 -2.29432304e+00 -2.49485958e+00 -8.16645816e+00 -4.91537406e+00
 -3.06743528e+00 -1.09848915e+00 -1.51148239e+00 -5.22116544e+00
 -1.92724628e+00 -1.56430645e+00 -2.25091508e+00 -1.97980312e+00
 -2.17638361e+00 -1.27177302e+00 -1.80603773e+00 -1.31155870e+00
 -1.48480152e+00 -8.98975618e-01 -7.04004676e-01 -1.85183810e+00
 -1.52281466e+00 -4.67087265e+00 -7.49468877e+00 -2.40900402e+00
 -3.93190978e+00 -3.25326975e+00 -2.75332081e+00 -3.01907774e+00
 -1.57917538e+00 -1.59348947e+00 -1.65763734e+00 -1.50241083e+00
 -1.34832053e+00 -1.42218207e+00 -1.46535813e+00 -1.44503573e+00
 -1.87505255e+00 -1.23023611e+00 -2.03710915e+00 -1.76628645e+00
 -2.39408453e+00 -3.13587170e+00 -2.90227673e+00 -2.14583195e+00
 -3.01938501e+00 -3.25713073e+00 -3.22135050e+00 -1.28597576e+00
 -4.36946067e+00 -5.55903554e+00 -3.84765390e-01 -1.23032560e+00
 -7.23995131e-01 -2.76744546e+00 -1.59796094e+00 -2.39190113e+00
 -2.22883924e+00 -3.18922155e+00 -1.35554982e+00 -2.79028314e+00
 -3.26846675e+00 -3.93977767e+00 -3.40953882e+00 -3.18552705e+00
 -1.40245577e+00 -1.75439970e+00 -4.79134804e+00 -1.58375423e+00
 -1.52784400e+00 -3.24680376e+00 -3.82247517e+00 -4.24323557e+00
 -4.02565124e+00 -6.33037395e+00 -1.31427604e+00 -5.74460323e+00
 -5.85540524e+00 -7.71641340e-01 -8.78312389e-01 -1.05215535e+00
 -5.13705954e-01 -5.09889111e+00 -5.42502785e+00 -5.33797074e+00
 -5.52600433e+00 -5.18876084e+00 -1.19519780e+00 -4.27401785e+00
 -1.42941549e+00 -5.53852591e+00 -1.63844480e+00 -5.53391366e+00
 -1.59828861e+00 -3.14085992e+00 -1.84715920e+00 -6.19632638e-01
 -3.73569864e+00 -3.34329222e+00 -1.90281948e+00 -2.16211019e+00
 -2.81795258e+00 -2.65095785e+00 -3.14436729e+00 -2.52385559e+00
 -2.94439795e+00 -3.05588257e+00 -2.75847687e+00 -3.20225879e+00
 -2.96764379e+00 -2.57968608e+00 -3.03189163e+00 -3.28176132e+00
 -6.06507130e+00 -4.54778122e-01 -3.88563523e+00 -1.47025686e+00
 -3.43107579e+00 -3.55440349e+00 -5.90239920e-01 -5.32926782e-01
 -7.97081044e+00 -1.40234386e+00 -1.86683849e+00 -5.88911449e-01
 -4.66342419e+00 -3.79683675e+00 -1.25299746e+00 -1.85267462e+00
 -1.21973306e+00 -1.10472821e+00 -5.70732874e-01 -1.21457164e+00
 -7.99688386e-01 -5.50034920e+00 -5.55338785e+00 -5.63610167e+00
 -1.79516253e+00 -1.87079814e+00 -1.02875357e+00 -1.82860997e+00
 -1.81346035e+00 -7.57640614e+00 -3.25701014e+00 -1.59349342e+00
 -2.06288078e+00 -5.16698074e+00 -5.39916839e-01 -6.60740978e-01
 -1.26936995e+00 -3.69303082e+00 -3.62107588e+00 -3.77982907e+00
 -3.48731008e+00 -3.67825539e+00 -6.60005320e-01 -6.58378854e-01
 -2.94354680e+00 -6.97321725e+00 -2.59997559e+00 -5.95405030e-01
 -3.02576629e+00 -1.52086663e+00 -1.64549833e+00 -3.15509113e-01
 -1.42489943e+00 -1.39178652e+00 -8.22619519e-01 -8.89426898e+00
 -9.79226065e-01 -7.61325944e-01 -3.57123321e-01 -3.85718920e-01
 -1.62731002e+00 -3.37294500e+00 -1.49491350e+00 -5.88690186e+00
 -4.89425830e+00 -3.66545166e+00 -3.06131213e+00 -2.67218435e+00
 -3.04106105e+00 -4.72620415e-01 -1.19377442e+01 -1.30749723e+00
 -2.96343388e+00 -2.43327770e+00 -5.95464716e+00 -5.15452003e+00
 -1.32824801e+00 -2.00572977e+00 -1.47447209e+00 -1.23812264e+00
 -2.31900210e+00 -6.54927228e+00 -3.61614454e+00 -3.48830934e+00
 -1.42250257e+00 -3.07777281e+00 -2.32328527e+00 -1.45486481e+00
 -5.25283937e+00 -5.24283674e+00 -3.70456875e+00 -6.69866755e-01
 -1.49952667e+00 -6.57612816e+00 -1.09274468e+00 -9.95034962e-01
 -7.50580482e-01 -2.68776978e+00 -2.81932616e+00 -2.99444333e+00
 -1.92343125e+00 -3.24116184e+00 -2.41271642e+00 -1.94926591e+00
 -2.04737278e+00 -6.77038960e-01 -1.62060302e+00 -7.40675586e-01
 -2.56974485e+00 -2.46509109e+00 -1.20256126e+00 -6.40398560e+00
 -2.35331044e+00 -3.04391462e+00 -1.02078131e+00 -6.97855063e+00
 -7.10109597e+00 -6.87526088e+00 -6.80760230e+00 -7.03597810e+00
 -3.48236318e+00 -2.43007207e+00 -7.09411442e+00 -2.36116950e+00
 -2.54434710e+00 -2.29124150e+00 -1.90339987e+00 -1.91462367e+00
 -1.07151924e+00 -4.56875923e+00 -4.78629919e+00 -4.39122854e+00
 -4.61753455e+00 -4.45797933e+00 -4.31552367e+00 -4.83147766e+00
 -4.53515837e+00 -4.69117636e+00 -5.12436830e+00 -4.90653959e+00
 -4.10736311e+00 -1.91606745e+00 -1.46271963e+01 -2.09328028e+00
 -1.97141062e+00 -2.03152354e+00 -2.07451569e+00 -3.35975034e+00
 -1.33278274e+00 -1.44095654e+00 -6.63485621e-01 -3.57793860e+00
 -3.86912895e+00 -3.35911812e+00 -6.82836875e+00 -6.00090949e+00
 -2.36529002e+00 -6.20557554e+00 -2.64791295e+00 -5.98812561e+00
 -5.78413620e+00 -1.04407884e+01 -1.02556262e+01 -8.61894122e-01
 -2.87643841e-01 -3.15759766e+00 -7.29170955e-01 -1.30032925e+00
 -8.16394212e-01 -3.35743642e+00 -8.82524169e-01 -7.64340512e-01
 -4.31767059e-01 -4.74188428e-01 -1.20464450e+00 -1.30197870e+00
 -8.44060011e-01 -7.55678705e-01 -8.98154587e-01 -1.13303467e+00
 -1.34820649e+00 -6.12647132e+00 -2.36618111e+00 -1.08054154e+00]

In [31]:
norm_test_data = pd.DataFrame(
    StandardScaler().fit_transform(test_data_short),
    columns=test_data_short.columns
)

In [32]:
test_pred = ridge.predict(norm_test_data)

In [33]:
test_pred

array([ 0.08119328,  0.08746653,  0.08626836,  0.08765432,  0.07846149,
        0.08350445,  0.08110218,  0.0785587 ,  0.08234014,  0.0822375 ,
        0.08123731,  0.08463925,  0.08129874,  0.08158711,  0.0816556 ,
        0.08471387,  0.0812196 ,  0.0792472 ,  0.08224482,  0.07726189,
        0.07677811,  0.08286787,  0.08096173,  0.08555299,  0.08658456,
        0.07447835,  0.07420984,  0.08666636,  0.0940181 ,  0.09166927,
        0.07426681,  0.07896233,  0.08751396,  0.07211257,  0.08677632,
        0.07712197,  0.08253023,  0.08413103,  0.09873133,  0.08414129,
        0.09121542,  0.08510445,  0.08401496,  0.08188358,  0.08170585,
        0.08369489,  0.08315415,  0.08268364,  0.08208583,  0.08345101,
        0.08290747,  0.08648949,  0.07933286,  0.09467553,  0.0947228 ,
        0.07995993,  0.09779667,  0.08846267,  0.07215369,  0.07499522,
        0.09916834,  0.09875268,  0.09764405,  0.09996516,  0.10137963,
        0.07113697,  0.0982829 ,  0.09983699,  0.09225291,  0.09060867,
        0.09150403,  0.092267  ,  0.08188599,  0.09061559,  0.09605909,
        0.08366188,  0.07286133,  0.07139292,  0.07151774,  0.0834321 ,
        0.08802265,  0.08602246,  0.07810311,  0.07894727,  0.05072749,
        0.05091791,  0.0928767 ,  0.09601388,  0.09109474,  0.09352051,
        0.09448677,  0.07788513,  0.10190688,  0.09750045,  0.10285933,
        0.08194363,  0.08547847,  0.09262567,  0.08443245,  0.075873  ,
        0.08545108,  0.08067895,  0.08401149,  0.09432373,  0.08829462,
        0.08057771,  0.07560667,  0.0772047 ,  0.09090392,  0.09387604,
        0.10392582,  0.10346803,  0.08070444,  0.07510677,  0.09238096,
        0.09066306,  0.10540018,  0.0740889 ,  0.09527632,  0.09428526,
        0.06995958,  0.09189664,  0.08511789,  0.09591204,  0.09881267,
        0.06907685,  0.09222499,  0.06844546,  0.10262732,  0.10367007,
        0.08594011,  0.06394439,  0.05841595,  0.07387219,  0.09690637,
        0.09506849,  0.08430893,  0.08212508,  0.08041637,  0.08572991,
        0.10608522,  0.09229134,  0.09198277,  0.09009253,  0.08095855,
       -0.06106487,  0.10650214,  0.08676375,  0.0874252 ,  0.09563093,
        0.0917114 ,  0.09228201,  0.08315976,  0.0967466 ,  0.09350394,
        0.09277793,  0.09406854,  0.09356228,  0.09539023,  0.09345696,
        0.09348791,  0.09969444,  0.09578281,  0.09186843,  0.10233859,
        0.10169296,  0.06790107,  0.08144517,  0.06854437,  0.08733615,
        0.08516275,  0.08863421,  0.07805749,  0.098886  ,  0.08483965,
        0.08551656,  0.08263922,  0.08150123,  0.06671016,  0.08061799,
        0.07895293,  0.08263908,  0.08507102,  0.08124331,  0.0839577 ,
        0.07891804,  0.06350337,  0.06236664,  0.07576272,  0.08007645,
        0.0756417 ,  0.08022711,  0.07772252,  0.07726596,  0.07567712,
        0.08943741,  0.08027413,  0.09541698,  0.09495841,  0.07652541,
        0.09460708,  0.07632622,  0.07668719,  0.07832951,  0.08022361,
        0.07401435,  0.07662843,  0.07630696,  0.07279609,  0.10476518,
        0.08663575,  0.07660153,  0.07734777,  0.07459754,  0.07104175,
        0.07255519,  0.07408583,  0.07381225,  0.07632722,  0.07184825,
        0.07540316,  0.10334852,  0.08245602,  0.07517158,  0.07823667,
        0.0838073 ,  0.09893504,  0.06955615,  0.08992424,  0.07243589,
        0.07096131,  0.06794459,  0.09471495,  0.07499262,  0.07739435,
        0.08181082,  0.09896644,  0.08873026,  0.09170897,  0.09402121,
        0.08823822,  0.08416606,  0.10309744,  0.06981975,  0.09393729,
        0.07708934,  0.09874636,  0.09854101,  0.08386808,  0.05599215,
        0.05560016,  0.05461236,  0.05721918,  0.05800278,  0.06733754,
        0.06596158,  0.05845657,  0.06680726,  0.07344447,  0.10464648,
        0.06758748,  0.08749924,  0.05689203,  0.07844901,  0.07764288,
        0.09416756,  0.08657477,  0.0757845 ,  0.08287393,  0.08888578,
        0.08167394,  0.08929957,  0.07866075,  0.0761906 ,  0.10042754,
        0.08946154,  0.08199778,  0.08597597,  0.09282168,  0.09804922,
        0.09821417,  0.07541997,  0.07588054,  0.07670008,  0.07375613,
        0.08805288,  0.09090027,  0.08861495,  0.06920697,  0.07994895,
        0.09947207,  0.07765024,  0.0791691 ,  0.06389833,  0.06434321,
        0.06439246,  0.07828337,  0.0917594 ,  0.07870036,  0.07865051,
        0.0947848 ,  0.09332751,  0.09410748,  0.09805617,  0.08407944,
        0.0760825 ,  0.07827923,  0.09979772,  0.0785245 ,  0.07191431,
        0.10241312,  0.08203619,  0.09556231,  0.09915511,  0.07576224,
        0.09216437,  0.09307341,  0.07663013,  0.08326092,  0.07904991,
        0.07286943,  0.07215469,  0.07712271,  0.06363325,  0.08199921,
        0.07430932,  0.0883909 ,  0.08710704,  0.08783053,  0.09850248,
        0.0818501 ,  0.07974629,  0.08777825,  0.06773025,  0.08385514,
        0.08392837,  0.08241129,  0.08256338,  0.08586168,  0.08212098,
        0.0880034 ,  0.0828946 ,  0.08327351,  0.08329444,  0.08309511,
        0.08351876,  0.10034359,  0.07839033,  0.09053118,  0.0669439 ,
        0.08158587,  0.0668824 ,  0.08416198,  0.08957549,  0.0890714 ,
        0.08086919,  0.06100997,  0.07128696,  0.08014839,  0.10006872,
        0.08059249,  0.07787376,  0.07721198,  0.07866137,  0.0758562 ,
        0.07671957,  0.08098652,  0.07751808,  0.07701912,  0.07822448,
        0.07742079,  0.07354058,  0.0876314 ,  0.08510365,  0.07787197,
        0.08463717,  0.07975688,  0.08019385,  0.09585874,  0.08530294,
        0.08288862,  0.10068345,  0.08096597,  0.08498948,  0.09140693,
        0.09210878,  0.09872034,  0.08111104,  0.09831751,  0.09884741,
        0.08596386,  0.08496017,  0.10119706,  0.08486664,  0.08473445,
        0.08434738,  0.08142424,  0.08095807,  0.09472403,  0.08224411,
        0.08309931,  0.0809129 ,  0.0833416 ,  0.08245512,  0.08311236,
        0.08422037,  0.08579422,  0.07905501,  0.09421945,  0.07495547,
        0.07428893,  0.07475068,  0.07432843,  0.07438202,  0.08494681,
        0.08524105,  0.08324925,  0.08313473,  0.08486592,  0.10316924,
        0.0869251 ,  0.06889217,  0.09663339,  0.07713561,  0.09162377,
        0.08326315,  0.09250282,  0.06222396,  0.08970044,  0.09281388,
        0.08059083,  0.08254223,  0.07940757,  0.07362191,  0.09037045,
        0.07359938,  0.08174606,  0.07622225,  0.07277786,  0.08168004,
        0.06763041,  0.08432521,  0.06689653,  0.07737369,  0.07320998,
        0.07817512,  0.07241634,  0.09549571,  0.07978752,  0.07266829,
        0.08234173,  0.08172391,  0.08614499,  0.06064048,  0.08107575,
        0.07600549,  0.08145057,  0.09009055,  0.08021314,  0.08148463,
        0.06785857,  0.0692843 ,  0.09653697,  0.08258931,  0.08004887,
        0.07120499,  0.08437387,  0.09804059,  0.1055628 ,  0.0722332 ,
        0.07375414,  0.08107559,  0.08028522,  0.07741548,  0.09372013,
        0.09434699,  0.09422246,  0.08296104,  0.09416267,  0.08514327,
        0.09086357,  0.09238475,  0.08403136,  0.07794066,  0.09342197,
        0.09217877,  0.08729022,  0.08051281,  0.08038479,  0.0805862 ,
        0.08063728,  0.08050748,  0.07030443,  0.0838431 ,  0.08030442,
        0.0744563 ,  0.07732121,  0.07830443,  0.08159926,  0.08301081,
        0.08438284,  0.06533542,  0.06632231,  0.06440442,  0.0655704 ,
        0.0647883 ,  0.06470939,  0.06705898,  0.0651695 ,  0.06592838,
        0.06963764,  0.06683502,  0.06941128,  0.07851476,  0.07459307,
        0.08067428,  0.07929779,  0.07979485,  0.08436365,  0.08178591,
        0.0846194 ,  0.08291811,  0.10374203,  0.07817281,  0.0795112 ,
        0.07956564,  0.08425886,  0.07009294,  0.07784183,  0.06834806,
        0.0984833 ,  0.07114825,  0.07247465,  0.0599202 ,  0.06006893,
        0.08728408,  0.09945668,  0.09014849,  0.08362032,  0.08206882,
        0.08371548,  0.08912927,  0.0832305 ,  0.0848585 ,  0.07464615,
        0.10463127,  0.09155637,  0.09079469,  0.09348286,  0.09518324,
        0.09479488,  0.08028813,  0.08076927,  0.07079125,  0.07942228,
        0.10221031])